//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uyanda.Coffee.Persistence.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coffee
    {
        public string CoffeeName { get; set; }
        public string CoffeeSize { get; set; }
    }
}
